[package]
name = "rusty_pickaxe"
version = "0.0.1"
edition = "2018"

[dependencies]
rustc-hex = "*"
tiny-keccak = {version = "2.0.2", features = ["keccak"]}
web3 = "0.17.0"
tokio = { version = "*", features = ["full"] }
secp256k1 = { version = "*", features = ["recovery"]}
